models:
  - name: hg-s8-b1-mpii
    launchers:
      - framework: dlsdk
        adapter:
          type: stacked_hourglass
          score_map_out: '4702'

    datasets:
      - name: mpii
        preprocessing:
          - type: object_crop_with_scale
            size: 256
        metrics:
          - type: pckh
            presenter: print_vector
