models:
- name: person-attributes-recognition-crossroad-0234
  launchers:
  - framework: dlsdk
    adapter:
      type: person_attributes
      attributes_recognition_out: 'attributes'
  datasets:
  - name: market_person_7_attributes
    data_source: Market1501-person-attributes-extra/annotation_test/data
    preprocessing:
    - type: crop_rect
    - type: resize
      dst_width: 80
      dst_height: 160
    metrics:
    - type: f1-score
      calculate_average: false
      presenter: print_vector

global_definitions: ../dataset_definitions.yml
