models:
  - name: tiny_yolo_v2

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/tiny_yolo_v2/FP32/tiny_yolo_v2.xml
        weights: public/tiny_yolo_v2/FP32/tiny_yolo_v2.bin
        adapter:
            type: yolo_v2
            anchors: "0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828"
            num: 5
            coords: 4
            classes: 80

      - framework: dlsdk
        tags:
          - FP16
        model:   public/tiny_yolo_v2/FP16/tiny_yolo_v2.xml
        weights: public/tiny_yolo_v2/FP16/tiny_yolo_v2.bin
        adapter:
            type: yolo_v2
            anchors: "0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828"
            num: 5
            coords: 4
            classes: 80

      - framework: dlsdk
        tags:
          - FP32-INT8
        model:   public/tiny_yolo_v2/FP32-INT8/tiny_yolo_v2.xml
        weights: public/tiny_yolo_v2/FP32-INT8/tiny_yolo_v2.bin
        adapter:
            type: yolo_v2
            anchors: "0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828"
            num: 5
            coords: 4
            classes: 80

      - framework: dlsdk
        tags:
          - FP16-INT8
        model:   public/tiny_yolo_v2/FP16-INT8/tiny_yolo_v2.xml
        weights: public/tiny_yolo_v2/FP16-INT8/tiny_yolo_v2.bin
        adapter:
            type: yolo_v2
            anchors: "0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828"
            num: 5
            coords: 4
            classes: 80

    datasets:
      - name: ms_coco_detection_80_class_without_background

        preprocessing:
          #- type: normalization
          #  std: 255.0
          - type: resize
            size: 416

        postprocessing:
          - type: resize_prediction_boxes
          - type: filter
            apply_to: prediction
            min_confidence: 0.001
            #min_confidence: 0.005
            remove_filtered: True
          #- type: correct_yolo_v2_boxes
          #  size: 416
          - type: nms
            overlap: 0.5
          - type: clip_boxes
            apply_to: prediction

        metrics:
          #- type: coco_orig_precision
          - type: map
            integral: 11point
            #ignore_difficult: true
            ignore_difficult: False
            presenter: print_scalar
          - type: coco_precision
            max_detections: 100
            threshold: 0.5
