models:
  - name: vas-person-vehicle-detection-stage1
    launchers:
    - framework: dlsdk
      inputs:
        - name: data
          type: INPUT
        - name: im_info
          type: CONST_INPUT
          value: [[544,960,0.5]]
      adapter:
        type: person_vehicle_detection
        iou_threshold: 0.45
    datasets:
    - name: mapillary
      data_source: mapillary/validation/images
      reader: opencv_imread
      annotation_conversion:
        converter: mapillary_detection_converter
        annotation_dir: mapillary/validation/annotations
        valid_gt_threshold: 0.05
      preprocessing:
      - type: resize
        interpolation: NEAREST
        dst_width: 960
        dst_height: 540
      - type: padding
        pad_type: right_bottom
        dst_width: 960
        dst_height: 544
        pad_value: 0,0,0
      metrics:
      - type: map
        overlap_threshold: 0.5
        include_boundaries: false
        overlap_method: iou
