models:
  - name: yolo-v3-tf

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   yolo-v3/tf/FP32/yolo-v3.xml
        weights: yolo-v3/tf/FP32/yolo-v3.bin
        adapter:
            type: yolo_v3
            anchors: "10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326"
            num: 9
            coords: 4
            classes: 80
            anchor_masks: [[6,7,8],[3,4,5],[0,1,2]]
            outputs:
              - detector/yolo-v3/Conv_6/BiasAdd/YoloRegion
              - detector/yolo-v3/Conv_14/BiasAdd/YoloRegion
              - detector/yolo-v3/Conv_22/BiasAdd/YoloRegion

      - framework: dlsdk
        tags:
          - FP16
        model:   yolo-v3/tf/FP16/yolo-v3.xml
        weights: yolo-v3/tf/FP16/yolo-v3.bin
        adapter:
            type: yolo_v3
            anchors: "10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326"
            num: 9
            coords: 4
            classes: 80
            anchor_masks: [[6,7,8],[3,4,5],[0,1,2]]
            outputs:
              - detector/yolo-v3/Conv_6/BiasAdd/YoloRegion
              - detector/yolo-v3/Conv_14/BiasAdd/YoloRegion
              - detector/yolo-v3/Conv_22/BiasAdd/YoloRegion

      - framework: dlsdk
        tags:
          - FP32-INT8
        model:   yolo-v3/tf/FP32-INT8/yolo-v3.xml
        weights: yolo-v3/tf/FP32-INT8/yolo-v3.bin
        adapter:
            type: yolo_v3
            anchors: "10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326"
            num: 9
            coords: 4
            classes: 80
            anchor_masks: [[6,7,8],[3,4,5],[0,1,2]]
            outputs:
              - detector/yolo-v3/Conv_6/BiasAdd/YoloRegion
              - detector/yolo-v3/Conv_14/BiasAdd/YoloRegion
              - detector/yolo-v3/Conv_22/BiasAdd/YoloRegion

      - framework: dlsdk
        tags:
          - FP16-INT8
        model:   yolo-v3/tf/FP16-INT8/yolo-v3.xml
        weights: yolo-v3/tf/FP16-INT8/yolo-v3.bin
        adapter:
            type: yolo_v3
            anchors: "10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326"
            num: 9
            coords: 4
            classes: 80
            anchor_masks: [[6,7,8],[3,4,5],[0,1,2]]
            outputs:
              - detector/yolo-v3/Conv_6/BiasAdd/YoloRegion
              - detector/yolo-v3/Conv_14/BiasAdd/YoloRegion
              - detector/yolo-v3/Conv_22/BiasAdd/YoloRegion

    datasets:
      - name: ms_coco_detection_80_class_without_backgound

        preprocessing:
          - type: resize
            size: 416

        postprocessing:
          - type: resize_prediction_boxes
          - type: filter
            apply_to: prediction
            min_confidence: 0.001
            remove_filtered: True
          - type: nms
            overlap: 0.5
          - type: clip_boxes
            apply_to: prediction

        metrics:
          - type: map
            integral: 11point
            ignore_difficult: true
            presenter: print_scalar
          - type: coco_precision
            max_detections: 100
            threshold: 0.5
