models:
  - name: yolo_v2

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/yolo_v2/FP32/yolo_v2.xml
        weights: public/yolo_v2/FP32/yolo_v2.bin
        adapter:
            type: yolo_v2
            anchors: "0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828"
            num: 5
            coords: 4
            classes: 80
            cells: 19

      - framework: dlsdk
        tags:
          - FP16
        model:   public/yolo_v2/FP16/yolo_v2.xml
        weights: public/yolo_v2/FP16/yolo_v2.bin
        adapter:
            type: yolo_v2
            anchors: "0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828"
            num: 5
            coords: 4
            classes: 80
            cells: 19


    datasets:
      - name: ms_coco_detection_80_class_without_background

        preprocessing:
          - type: resize
            size: 608

        postprocessing:
          - type: resize_prediction_boxes
          - type: filter
            apply_to: prediction
            min_confidence: 0.001
            remove_filtered: True
          - type: nms
            overlap: 0.5
          - type: clip_boxes
            apply_to: prediction

        metrics:
          - type: map
            integral: 11point
            ignore_difficult: true
            presenter: print_scalar
          - type: coco_precision
            max_detections: 100
            threshold: 0.5

global_definitions: ../dataset_definitions.yml
